- alias: 'Gang beweging'
  trigger:
    - platform: state
      entity_id: binary_sensor.gang_motion_sensor
      to: 'on'
  condition:
      condition: or 
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.gang

- alias: 'Gang geen beweging'
  trigger:
    - platform: state
      entity_id: binary_sensor.gang_motion_sensor
      to: 'off'
      for:
          minutes: 1
  condition:
      condition: or 
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
        - condition: state
          entity_id: light.gang
          state: 'on'
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.gang